name: Build radmat image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest@sha256:08795a40a232d47bdf6cb90913a76af449dbfcddfc36d598a050f57d67e4b54b
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Login to registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ vars.IMAGE_REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME}}
          password: ${{ secrets.REGISTRY_TOKEN}}

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: .
          cache-from: type=registry,ref=${{ vars.IMAGE_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}
          cache-to: type=inline
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ vars.IMAGE_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ steps.meta.outputs.REPO_VERSION }}
            ${{ vars.IMAGE_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:latest
